name: Build and Test

# Trigger on push or pull request
on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
    branches:
      - master
      - develop
  push:
    branches:
      - master
      - develop

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      # Send slack notification that the build process has started
      - uses: 8398a7/action-slack@v3
        with:
          author_name: 'Android Build and Test'
          fields: repo,author,eventName,message,commit
          status: ${{ job.status }}
          text: 'Build started'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        if: always() # Pick up events even if the job fails or is canceled.
      
      # Clone the repo
      - name: Clone the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          fetch-depth: 0

      # Replace the "dummy" google-services.json with a real one (ACME account)
      - name: Replace google-services.json in the project
        env:
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
        run: echo $GOOGLE_SERVICES > samples/authenticator/google-services.json

      # Setup JDK and cache and restore dependencies.
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'gradle'
      
      # Execute unit tests
      - name: Run unit tests
        run: ./gradlew test --stacktrace

      # Publish test reports for the unit tests
      - name: Publish test results
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Unit tests results
          path: 'forgerock-core/build/test-results/**/TEST-*.xml,forgerock-auth/build/test-results/**/TEST-*.xml,forgerock-authenticator/build/test-results/**/TEST-*.xml'
          list-suites: 'all'
          list-tests: 'all'
          fail-on-error: 'true'
          reporter: java-junit

      - uses: 8398a7/action-slack@v3
        with:
          author_name: 'Android Build and Test'
          mention: 'stoyan.petrov'
          if_mention: 'failure,cancelled'
          fields: repo,author,eventName,message,commit,took
          status: ${{ job.status }}
          text: 'Build finished!'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        if: always()