name: Build and Test
on:
  workflow_call:
    inputs:
      runs-on:
        description: Platform to execute on
        type: string
        default: macos-latest
    secrets:
      SLACK_WEBHOOK:
        description: Slack Notifier Incoming Webhook
        required: true
jobs:
  build-and-test:
    runs-on: ${{ inputs.runs-on }}

    steps:
      # Clone the repo
      - name: Clone the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          fetch-depth: 0

      # Setup JDK and cache and restore dependencies.
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'gradle'

      # Execute forgerock-core debug unit tests
      - name: Run forgerock-core debug unit tests
        run: ./gradlew :forgerock-core:testDebugUnitTest --stacktrace --no-daemon
        
      # Execute forgerock-auth debug unit tests
      - name: Run forgerock-auth debug unit tests
        run: ./gradlew :forgerock-auth:testDebugUnitTest --stacktrace --no-daemon

      # Execute forgerock-authenticator debug unit tests
      - name: Run forgerock-authenticator debug unit tests
        run: ./gradlew :forgerock-authenticator:testDebugUnitTest --stacktrace --no-daemon

      # Publish test reports for the unit tests
      - name: Publish test results
        if: success() || failure()
        uses: dorny/test-reporter@v1
        with:
          name: Unit tests results
          path: 'forgerock-core/build/test-results/**/TEST-*.xml,forgerock-auth/build/test-results/**/TEST-*.xml,forgerock-authenticator/build/test-results/**/TEST-*.xml'
          list-suites: 'all'
          list-tests: 'all'
          fail-on-error: 'true'
          reporter: java-junit

      # Send slack notification with result status
      - uses: 8398a7/action-slack@v3
        with:
          mention: 'stoyan.petrov,andy.witrisna,jey.periyasamy'
          if_mention: 'failure,cancelled'
          fields: repo,author,eventName,message,job,pullRequest,took
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        if: always()