name: Run Sonatype OSS Index Scan
on:
  workflow_call:
    secrets:
      SONATYPE_USERNAME:
        description: Sonatype OSS Index username
        required: true
      SONATYPE_PASSWORD:
        description: Sonatype OSS Index password
        required: true
      SLACK_WEBHOOK:
        description: Slack Notifier Incoming Webhook
        required: true
      
jobs:
  sonatype-ossi-scan:
    runs-on: ubuntu-latest

    steps:
      # Clone the repo
      - name: Clone the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          fetch-depth: 0

      # Setup JDK and cache and restore dependencies.
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      # Execute Sonatype OSS Index scan
      - name: Execute Sonatype OSS Index scan
        run: ./gradlew ossIndexAudit -Dusername=${{ secrets.SONATYPE_USERNAME }} -Dpassword=${{ secrets.SONATYPE_PASSWORD }} --no-daemon
        
      # Send slack notification with result status
      - uses: 8398a7/action-slack@v3
        with:
          mention: 'stoyan.petrov,andy.witrisna,jey.periyasamy'
          if_mention: 'failure,cancelled'
          fields: repo,author,eventName,message,job,pullRequest,took
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        if: always()